### PR TITLE
fix: added validation to check whether the Notion page is public or private

### LINKED ISSUE #221: 🐛 Bug: The preview site crashes when a private Notion page link gets added
## Description
**When a user adds a private Notion page link, the preview site crashes**. This issue is specific to private Notion links and does not occur with public links.

## Steps to Reproduce
1. While adding the link, we need to check if the Notion page link is private or public. If it's private, we will send an error message, otherwise, we will add the page link.

 ## Bug Preview

https://github.com/mfts/papermark/assets/87828904/b1976c2e-e256-4321-bd01-5f4c346b24c9

## Would you like to work on this issue?

**Yes, I would like to work on this issue**

### PR DESCRIPTION
**Pull request by ashrafchowdury**
## Description
**Added validation to check whether the Notion page is publically accessible or not.** If the Notion page is not accessible it will terminate the process and will return an error message to the user.

## Changes
1. Validation added to check if the Notion page is publically accessible before saving to the database.
2. Implemented try-catch to handle errors and prevent global error messages.
3. Updated the user-facing error message to clarify the issue properly

## Preview

https://github.com/mfts/papermark/assets/87828904/0d24c3b4-23b3-40ff-825f-8b8cdb0582e8

## Issue

Closes #221

### CODE REVIEW

File: pages/api/teams/[teamId]/documents/index.ts [hunk 1]
```diff
@@ -84,7 +86,14 @@ export default async function handle(
...
 
-      // You could perform some validation here
+      // Check whether the Notion page is publically accessible or not
+      try {
+        const pageId = parsePageId(fileUrl, { uuid: false });
+        // if the page isn't accessible then end the process here.
+        await notion.getPage(pageId);
+      } catch (error) {
+        return res.status(404).end("This Notion page isn't publically available.");
+      }
```
Comment (mfts) [inline pages/api/teams/[teamId]/documents/index.ts]: Check if the `type === "notion"` otherwise, this will throw an error for regular documents as the backend function is shared

**Review by mfts — CHANGES_REQUESTED** [review]

File: pages/api/teams/[teamId]/documents/index.ts (hunk 1 above)
Comment (ashrafchowdury) [reply pages/api/teams/[teamId]/documents/index.ts]: Sounds good 👍
